import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@breeze/ui/globals.css";
import "./globals.css";
import NavBar from "@/components/NavBar";
import TimelineFooter from "@/components/TimeLineFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <TimelineFooter />
      </body>
    </html>
  );
}
